import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs';
import { Provider as TooltipProvider } from "@radix-ui/react-tooltip";
import AppProvider from "./provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <AppProvider>
            <TooltipProvider>
              {children}
              <Toaster/>
            </TooltipProvider>
          </AppProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
